import type { Appointment, DoctorTeam, DutyTemplate, Person, VetId } from "./types.ts";
import { inferKit } from "./kit.ts";

export const STAFF: Person[] = [
  {
    id: "alejandro",
    name: "Alejandro",
    short: "Alejandro",
    kind: "primary-tech",
    workdays: [1, 2, 3, 4, 5],
    onCallDays: [],
    usualTeam: "weston",
    usualRole: "primary",
    surgery: true,
    notes: "Required primary on every Weston appointment, including surgery.",
  },
  {
    id: "becca",
    name: "Becca",
    short: "Becca",
    kind: "support-tech",
    workdays: [1, 2, 4, 5],
    onCallDays: [0],
    usualTeam: "sidney",
    usualRole: "primary",
    surgery: false,
    notes: "Sidney’s preferred tech. Can be Weston’s second when Sidney does not need her.",
  },
  {
    id: "kaycee",
    name: "Kaycee",
    short: "Kaycee",
    kind: "support-tech",
    workdays: [2, 3, 4, 5],
    onCallDays: [],
    usualTeam: "weston",
    usualRole: "secondary",
    surgery: false,
    notes: "First-choice second tech for Weston when free.",
  },
  {
    id: "alice",
    name: "Alice",
    short: "Alice",
    kind: "support-tech",
    workdays: [],
    onCallDays: [],
    usualTeam: "float",
    usualRole: "float",
    surgery: false,
    hoursPerWeek: 30,
    notes: "Float. Same pool as Kaycee for Weston’s second-tech slot.",
  },
  {
    id: "kate",
    name: "Kate",
    short: "Kate",
    kind: "office",
    workdays: [1, 2, 3, 4, 5],
    onCallDays: [],
    usualTeam: "office",
    usualRole: "office",
    surgery: false,
    notes: "Office manager. Never counts as clinical coverage.",
  },
];

export const DOCTORS: DoctorTeam[] = [
  { vetId: "weston", name: "Weston Davis", label: "Dr. Davis", truck: "Dr. Davis's truck", needsTwo: true },
  { vetId: "sidney", name: "Sidney Chanutin", label: "Dr. Chanutin", truck: "Chanutin truck", needsTwo: false },
  { vetId: "michaela", name: "Michaela Dooley", label: "Dr. Dooley", truck: "Dr. Dooley's truck", needsTwo: false },
];

export const VETS: Record<VetId, { name: string; label: string }> = {
  weston: { name: "Weston Davis", label: "Dr. Davis" },
  sidney: { name: "Sidney Chanutin", label: "Dr. Chanutin" },
  michaela: { name: "Michaela Dooley", label: "Dr. Dooley" },
};

export const DUTY_TEMPLATES: DutyTemplate[] = [
  { id: "p-rads", label: "Radiographs and ultrasound", when: "during", role: "primary" },
  { id: "p-equip", label: "Prepare specialized equipment", when: "during", role: "primary" },
  { id: "p-coord", label: "Coordinate the medical workflow with the doctor", when: "during", role: "primary" },
  { id: "s-jog", label: "Jog horses", when: "during", role: "secondary" },
  { id: "s-hvms", label: "Enter invoices in HVMS after each appointment", when: "during", role: "secondary" },
  { id: "s-dea", label: "Log controlled drugs in the Control Log", when: "during", role: "secondary" },
  { id: "s-xfer", label: "Transfer images", when: "eod", role: "secondary" },
  { id: "s-send", label: "Send images to clients (same day)", when: "eod", role: "secondary" },
  { id: "s-blood", label: "Send or document bloodwork", when: "eod", role: "secondary" },
  { id: "s-clean", label: "Clean equipment", when: "eod", role: "secondary" },
  { id: "s-truck", label: "Restock {truck}", when: "eod", role: "secondary" },
  { id: "s-supplies", label: "Prepare supplies for tomorrow", when: "eod", role: "secondary" },
  { id: "s-docs", label: "Confirm all documentation is complete", when: "eod", role: "secondary" },
  { id: "f-support", label: "Support whichever team is busiest", when: "during", role: "float" },
  { id: "f-ops", label: "Operational work", when: "during", role: "float" },
  { id: "a-sterile", label: "Sterile prep", when: "during", personId: "alejandro" },
  { id: "a-bio", label: "Sterile draw-up of biologics", when: "during", personId: "alejandro" },
  { id: "a-run", label: "Keep the day running smoothly", when: "during", personId: "alejandro" },
  { id: "sx-pack", label: "Stage the surgery pack", when: "during", personId: "alejandro", surgeryOnly: true },
];

export const WEEK_DATES = [
  "2026-09-14",
  "2026-09-15",
  "2026-09-16",
  "2026-09-17",
  "2026-09-18",
  "2026-09-19",
];

export const DEMO_FOCUS_DATE = "2026-09-15";

export const APPOINTMENTS: Appointment[] = ([
  {
    id: "m14-w1",
    date: "2026-09-14",
    start: "09:00",
    end: "11:00",
    title: "Helgstrand — Benny repeat blocking",
    location: "Wellington",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "m14-s1",
    date: "2026-09-14",
    start: "08:15",
    end: "09:15",
    title: "Rading — Chammie",
    location: "Wellington",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "m14-s2",
    date: "2026-09-14",
    start: "09:00",
    end: "11:30",
    title: "Andrews — lasers and bloodwork",
    location: "Wellington",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "m14-d1",
    date: "2026-09-14",
    start: "09:00",
    end: "10:15",
    title: "Sedate lip for Valdo",
    location: "Clinic",
    vetId: "michaela",
    service: "field",
    colorLabel: "Wisteria",
  },
  {
    id: "t15-w1",
    date: "2026-09-15",
    start: "09:00",
    end: "12:00",
    title: "Serda — Jazzy 7-site kissing spine",
    location: "Hospital",
    vetId: "weston",
    service: "surgery",
    colorLabel: "Tomato",
  },
  {
    id: "t15-w2",
    date: "2026-09-15",
    start: "12:00",
    end: "13:30",
    title: "Gore — Gally standing sx",
    location: "Polo tx room",
    vetId: "weston",
    service: "surgery",
    colorLabel: "Tomato",
  },
  {
    id: "t15-s1",
    date: "2026-09-15",
    start: "09:30",
    end: "13:30",
    title: "Wilberg — lameness workups",
    location: "Parkland",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "t15-s2",
    date: "2026-09-15",
    start: "14:00",
    end: "17:00",
    title: "Weinwurm PPE",
    location: "Loxahatchee",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "w16-w1",
    date: "2026-09-16",
    start: "09:00",
    end: "09:30",
    title: "Brown — Oliver sarcoid eval",
    location: "Clinic",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "w16-w2",
    date: "2026-09-16",
    start: "10:00",
    end: "11:00",
    title: "KS Leiner — shockwave",
    location: "Loxahatchee",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "th17-w1",
    date: "2026-09-17",
    start: "09:00",
    end: "12:00",
    title: "Cantu — stifle / airway consults",
    location: "Clinic",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "th17-s1",
    date: "2026-09-17",
    start: "15:00",
    end: "17:00",
    title: "Ewing — lameness",
    location: "Field",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "f18-s1",
    date: "2026-09-18",
    start: "12:15",
    end: "13:15",
    title: "Jones — Leo FES back",
    location: "Wellington",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "sa19-w1",
    date: "2026-09-19",
    start: "10:00",
    end: "11:30",
    title: "Delboni — George recheck",
    location: "Clinic",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
] as Appointment[]).map((a) => ({ ...a, kit: a.kit ?? inferKit(a.title) }));
