import type { Appointment, Person } from "./types.ts";

export const STAFF: Person[] = [
  {
    id: "alejandro",
    name: "Alejandro",
    short: "Alejandro",
    kind: "primary-tech",
    workdays: [1, 2, 3, 4, 5, 6],
    notes: "Required primary on every Weston appointment. Rads, ultrasound, advanced support.",
  },
  {
    id: "becca",
    name: "Becca",
    short: "Becca",
    kind: "support-tech",
    workdays: [1, 2, 3, 5, 6],
    notes: "Sidney’s preferred tech. Can be Weston’s second when Sidney does not need her.",
  },
  {
    id: "kaycee",
    name: "Kaycee",
    short: "Kaycee",
    kind: "support-tech",
    workdays: [1, 2, 4, 5, 6],
    notes: "Flexible support. First-choice second tech for Weston when free.",
  },
  {
    id: "alice",
    name: "Alice",
    short: "Alice",
    kind: "support-tech",
    workdays: [3, 4, 6],
    notes: "Flexible support. Same pool as Kaycee for Weston’s second-tech slot.",
  },
  {
    id: "kate",
    name: "Kate",
    short: "Kate",
    kind: "office",
    workdays: [1, 2, 3, 4, 5],
    notes: "Office manager. Never counts as clinical coverage.",
  },
];

export const VETS: Record<
  "weston" | "sidney" | "michaela",
  { name: string; label: string }
> = {
  weston: { name: "Weston Davis", label: "Dr. Davis" },
  sidney: { name: "Sidney Chanutin", label: "Dr. Sidney" },
  michaela: { name: "Michaela Doole", label: "Dr. Doole" },
};

export const WEEK_DATES = [
  "2026-09-14",
  "2026-09-15",
  "2026-09-16",
  "2026-09-17",
  "2026-09-18",
  "2026-09-19",
];

export const DEMO_FOCUS_DATE = "2026-09-15";

export const APPOINTMENTS: Appointment[] = [
  {
    id: "m14-w1",
    date: "2026-09-14",
    start: "08:00",
    end: "12:30",
    title: "Sports med — Wellington barns",
    location: "Wellington",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "m14-s1",
    date: "2026-09-14",
    start: "09:00",
    end: "13:00",
    title: "Barn calls",
    location: "Loxahatchee",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "t15-w1",
    date: "2026-09-15",
    start: "08:00",
    end: "12:00",
    title: "Lameness workups",
    location: "Palm Beach Polo",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "t15-w2",
    date: "2026-09-15",
    start: "13:00",
    end: "16:30",
    title: "Follow-ups and injections",
    location: "Wellington",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "t15-s1",
    date: "2026-09-15",
    start: "08:30",
    end: "12:00",
    title: "PPE and barn calls",
    location: "Loxahatchee",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "t15-d1",
    date: "2026-09-15",
    start: "08:30",
    end: "12:00",
    title: "Riding with Sidney",
    location: "Loxahatchee",
    vetId: "michaela",
    service: "field",
    colorLabel: "Wisteria",
    notes: "Follows Sidney — no dedicated tech line.",
  },
  {
    id: "w16-s1",
    date: "2026-09-16",
    start: "08:30",
    end: "15:00",
    title: "Field day",
    location: "West Palm / Jupiter",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "w16-d1",
    date: "2026-09-16",
    start: "08:30",
    end: "15:00",
    title: "With Sidney",
    location: "West Palm / Jupiter",
    vetId: "michaela",
    service: "field",
    colorLabel: "Wisteria",
  },
  {
    id: "th17-w1",
    date: "2026-09-17",
    start: "07:30",
    end: "13:00",
    title: "Arthroscopy",
    location: "Hospital",
    vetId: "weston",
    service: "surgery",
    colorLabel: "Tomato",
  },
  {
    id: "th17-s1",
    date: "2026-09-17",
    start: "09:00",
    end: "14:00",
    title: "Barn calls",
    location: "Wellington",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "f18-w1",
    date: "2026-09-18",
    start: "08:00",
    end: "12:00",
    title: "Sports med",
    location: "Palm Beach Polo",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "f18-w2",
    date: "2026-09-18",
    start: "13:00",
    end: "16:00",
    title: "Ultrasound follow-ups",
    location: "Wellington",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
  {
    id: "f18-s1",
    date: "2026-09-18",
    start: "08:30",
    end: "13:30",
    title: "Lameness + PPE",
    location: "Loxahatchee",
    vetId: "sidney",
    service: "field",
    colorLabel: "Flamingo",
  },
  {
    id: "sa19-w1",
    date: "2026-09-19",
    start: "08:00",
    end: "14:00",
    title: "Saturday sports med",
    location: "Wellington",
    vetId: "weston",
    service: "sports",
    colorLabel: "Peacock",
  },
];

export const TASK_TEMPLATES: { label: string; required: boolean; surgeryOnly?: boolean }[] = [
  { label: "Invoices entered in HVMS", required: true },
  { label: "Images transferred off the machine", required: true },
  { label: "Images sent to client", required: true },
  { label: "DEA drug log completed", required: true, surgeryOnly: true },
  { label: "Truck restocked", required: true },
  { label: "Equipment cleaned", required: true },
  { label: "Bloodwork sent or documented", required: false },
  { label: "Supplies staged for tomorrow", required: true },
];
